# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Westgeest Psychologie Praktijk Tilburg
email: info@westgeest-psychologie.nl
phone: 06-49806043
linkedin_username: christina-westgeest-007507b
address: <a href="https://goo.gl/maps/pWgwjrjoek14GBFo9" target="_blank">Kapitein Rondairestraat 3<br/>5015 BC Tilburg</a>
description: >- # this means to ignore newlines until "baseurl:"
  Praktijk voor psychologie in Tilburg en Hilvarenbeek. Voor psychologische therapie 
  relatietherapie ondersteuning en advies.
url: "https://westgeest-psychologie.nl" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  rwestgeest
locale: nl_NL

google_analytics: UA-178363440-1

minima:
  date_format: "%d-%m-%Y"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

header_pages:
  - voor-jou.md
  - voor-je-relatie.md
  - voor-je-gezin.md
  - tarieven.md
  - over-christina.md
  - contact.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - run.sh
  - docker-compose.yml
  - README.md

