version: '2'

services:
  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - .:/site
    ports:
      - '8092:4000'
      - '35739:35739'
    command: bundle exec jekyll s --drafts --force-polling -H 0.0.0.0 -P 4000 --livereload --livereload_port 35739
